name: Publish to NPM

on:
  workflow_dispatch:  # Manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Check if version exists
        id: version_check
        run: |
          # Get version from package.json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $PACKAGE_VERSION"
          
          # Check if tag exists
          if git rev-parse "v$PACKAGE_VERSION" >/dev/null 2>&1; then
            echo "Version $PACKAGE_VERSION already exists as a tag!"
            exit 1
          fi
          
          # Check if version exists on npm
          if npm view . versions 2>/dev/null | grep -q "\"$PACKAGE_VERSION\""; then
            echo "Version $PACKAGE_VERSION already exists on npm!"
            exit 1
          fi
          
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ steps.version_check.outputs.version }}" -m "Release v${{ steps.version_check.outputs.version }}"
          git push origin "v${{ steps.version_check.outputs.version }}"

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}